name: gonfi_domain
decription: 'This is the domain layer of the Confi-App'

dependencies:
  built_value: '^5.4.3'
  rxdart: "^0.16.7"

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dev_dependencies:
  build_runner: ^0.7.9
  built_value_generator: '^5.4.3'
  quiver: '>=0.21.0 <0.30.0'
  mockito: "^2.2.3"
  test: any