name: gonfi
description: DevFest App

dependencies:
  gonfi_domain:
    path: ../domain
  #app-layer
  flutter_redux: "^0.5.0"
  firebase_auth: "^0.5.10"
  google_sign_in: "^3.0.3+1"
  rxdart: "^0.16.7"
  #ui-layer
  flutter:
    sdk: flutter
<<<<<<< HEAD:pubspec.yaml
  flutter_redux: "^0.5.0"
  intl: "^0.15.2"
  intl_translation: "^0.16.1"
=======
  flutter_localizations:
      sdk: flutter
>>>>>>> feature/auth:app/pubspec.yaml
  cached_network_image: "^0.3.0"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: GoogleSans
      fonts:
      - asset: res/fonts/GoogleSans-Regular.ttf
        weight: 400
      - asset: res/fonts/GoogleSans-Medium.ttf
        weight: 500
    - family: LibreFranklin
      fonts:
        - asset: res/fonts/LibreFranklin-Light.ttf
          weight: 300
        - asset: res/fonts/LibreFranklin-Regular.ttf
          weight: 400
        - asset: res/fonts/LibreFranklin-Medium.ttf
          weight: 500
